service:
  name: facebook-assistant-api

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

functions:
  get-session:
    handler: dist/functions/getSession.handler
    description: Gets the information collected in a particular session
    events:
      - http:
          method: get
          path: /sessions/{id}
          request:
            parameters:
              paths:
                id: true
  get-sessions:
    handler: dist/functions/getSessions.handler
    description: Gets a list of all sessions
    events:
      - http:
          method: get
          path: /sessions
  send-webhook-watson:
    handler: dist/functions/sendWebhookWatson.handler
    description: Receives and handles the Watson Assistant collected information
    events:
      - http:
          method: post
          path: /webhook/watson
