service:
  name: facebook-assistant-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'} # Set the default stage used. Default is dev
  region: ${opt:region, 'us-east-1'} # Overwrite the default region used. Default is us-east-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

functions:
  health: # A Function
    handler: dist/functions/checkHealth.handler # The file and module for this specific function
    description: Checks the service health # The description of your function.
    events: # The Events that trigger this Function
      - http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function
          method: get
          path: /health
  get-session:
    handler: dist/functions/getSession.handler
    description: Gets the information collected in a particular session
    events:
      - http:
          method: get
          path: /sessions/{id}
          request:
            parameters:
              paths:
                id: true
  get-sessions:
    handler: dist/functions/getSessions.handler
    description: Gets a list of all sessions
    events:
      - http:
          method: get
          path: /sessions
  webhook-watson:
    handler: dist/functions/sendWebhookWatson.handler
    description: Receives the Watson Assistant collected information
    events:
      - http:
          method: post
          path: /webhook/watson
